<a href="https://colab.research.google.com/github/helaena-lianne/sales-dataclean/blob/main/sales_dataclean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Cleaning

In [64]:
## import statements

import os
import re
import PIL
import numpy as np
import pandas as pd
import seaborn as sns
from joblib import dump, load
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
df = pd.read_csv("/content/drive/MyDrive/datasets/Sales_Dataset_2024.csv")
display(df)

,Date,Region,Product,Salesperson,Units_Sold,Unit_Price,Category,Revenue,Cost,Profit
0,4/12/2024 0:00,North,Smartwatch,Hannah,15.0,1224.0,Accessories,18360.0,16451.634260,1908.365742
1,12/14/2024 0:00,North,Monitor,Eva,5.0,1321.0,Office,6605.0,4457.351727,2147.648273
2,9/27/2024 0:00,North,Mobile,Bob,11.0,912.0,Electronics,10032.0,6563.644126,3468.355874
3,4/16/2024 0:00,West,Monitor,Charlie,18.0,325.0,Office,5850.0,4320.807092,1529.192908
4,3/12/2024 0:00,West,Headphones,Eva,13.0,1042.0,Accessories,13546.0,8270.122666,5275.877334
...,...,...,...,...,...,...,...,...,...,...
1995,10/10/2024 0:00,East,Headphones,David,3.0,1333.0,Accessories,3999.0,3227.051448,771.948552
1996,4/30/2024 0:00,North,Tablet,Alice,6.0,703.0,Electronics,4218.0,3249.244924,968.755076
1997,4/16/2024 0:00,North,Smartwatch,Grace,7.0,1760.0,Accessories,12320.0,8980.011984,3339.988016
1998,6/23/2024 0:00,South,Printer,Charlie,1.0,1114.0,Office,1114.0,941.813213,172.186787
1999,7/22/2024 0:00,West,Tablet,Frank,1.0,1196.0,Electronics,1196.0,1002.640577,193.359423

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         2000 non-null   object
 1   Region       1961 non-null   object
 2   Product      1960 non-null   object
 3   Salesperson  1960 non-null   object
 4   Units_Sold   1960 non-null   float64
 5   Unit_Price   1960 non-null   float64
 6   Category     2000 non-null   object
 7   Revenue      1921 non-null   float64
 8   Cost         1921 non-null   float64
 9   Profit       1921 non-null   float64
dtypes: float64(5), object(5)
memory usage: 156.4+ KB

drop duplicate rows

In [67]:
print(f"Number of duplicates: {df.duplicated().sum()}")
df.drop_duplicates(inplace=True)
print(f"Number of duplicates after: {df.duplicated().sum()}")

Number of duplicates: 0
Number of duplicates after: 0

displays the number of null values

In [68]:
df.isnull().sum()
df.isna().sum()

Date            0
Region         39
Product        40
Salesperson    40
Units_Sold     40
Unit_Price     40
Category        0
Revenue        79
Cost           79
Profit         79
dtype: int64

drop the rows with null values

In [69]:
df = df.dropna()

converts the date column to a datetime datatype then drops the time portion

In [70]:
df["Date"] = pd.to_datetime(df["Date"])
df["Date"] = df["Date"].dt.date

displays the unique values of the Region column

In [71]:
df["Region"].unique()

array(['North', 'West', 'East', 'South', 'south', 'westt', 'Easst',
       'NORTH', 'north'], dtype=object)

corrects the mispelled values and corrects the cases for uniformity

In [72]:
df["Region"] = df["Region"].replace({
    "westt": "West",
    "Easst": "East",
    "NORTH": "North",
    "north":"North",
    "south":"South"
})

In [73]:
df["Region"].unique()

array(['North', 'West', 'East', 'South'], dtype=object)

displays the unique values of the Product column

In [74]:
df["Product"].unique()

array(['Smartwatch', 'Monitor', 'Mobile', 'Headphones', 'Camera',
       'Laptop', 'Printer', 'Tablet', 'tabllet', 'MOBLIE', 'SMARTWATCH',
       'headPhones', 'laptop'], dtype=object)

In [75]:
df["Product"] = df["Product"].replace({
    "tabllet": "Tablet",
    "MOBLIE": "Mobile",
    "SMARTWATCH": "Smartwatch",
    "headPhones":"Headphones",
    "laptop":"Laptop"
})

In [76]:
df["Product"].unique()

array(['Smartwatch', 'Monitor', 'Mobile', 'Headphones', 'Camera',
       'Laptop', 'Printer', 'Tablet'], dtype=object)

In [77]:
df["Salesperson"].unique()

array(['Hannah', 'Eva', 'Bob', 'Charlie', 'Grace', 'Alice', 'Frank',
       'David'], dtype=object)

In [78]:
df["Category"].unique()

array(['Accessories', 'Office', 'Electronics'], dtype=object)

converts the dataframe to csv

In [79]:
df.to_csv('sales_data.csv', index=False)
print("DataFrame saved to sales_data.csv")

DataFrame saved to sales_data.csv